name: Build & Qodana
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Qodana - License Audit
        uses: JetBrains/qodana-license-audit-action@v2.0-eap
